#!/bin/bash


function _execCommand ()
{
	"$SG_SCRIPT_PATH/sgcheck-bin/$1" $2 # <- no " here, so it expands to possibly more than one option!
}

function _execCommandSafe ()
{
	if [ ! -e "$SG_SCRIPT_PATH/sgcheck-bin/$1" ]; then
		echo -e "invalid command!"
	else
		echo "gonna execute $SG_SCRIPT_PATH/sgcheck-bin/$1 $2"
		_execCommand "$1" "$2"
	fi
}


# all parameters as one single string:
allArgs=( "$@" )
subscript="$1"
subscript_opts=( "${allArgs[@]:1 }" )

if [ ! "$subscript" = "" ]; then
	_execCommandSafe "$subscript" "${subscript_opts[*]}"
	exit 0
fi


clear
echo -e "************************************"
echo -e "* sgcheck                          *"
echo -e "************************************"


# complete -F _compFunc

selection=
until [ "selection" = "$CMD_EXIT" ]; do

	echo -en "> "
	read selection
	_execCommandSafe "$selection"
done


