#!/bin/bash


function _execCommand ()
{
	"$SG_SCRIPT_PATH/sgcheck-bin/$1"
}

function _execCommandSafe ()
{
	if [ ! -e "$SG_SCRIPT_PATH/sgcheck-bin/$1" ]; then
		echo -e "invalid command!"
	else
		echo "gonna execute $SG_SCRIPT_PATH/sgcheck-bin/$1"
		_execCommand "$1"
	fi
}


subscript="$1"

if [ ! "$subscript" = "" ]; then
	_execCommandSafe "$subscript"
	exit 0
fi


clear
echo -e "************************************"
echo -e "* sgcheck                          *"
echo -e "************************************"


# complete -F _compFunc

selection=
until [ "selection" = "$CMD_EXIT" ]; do

	echo -en "> "
	read selection
	_execCommandSafe "$selection"
done


