#!/bin/bash

# Setting variables (loaded by using the "init" function):
#SETTINGS_FOLDER
#SETTINGS_FILE
#SERVER
#THIS
#SERVER_BASE
#THIS_BASE

CMD_EXIT="exit"

# include global functions
. $SG_SCRIPT_PATH/sgcheck-bin/util/global
. $SG_SCRIPT_PATH/sgcheck-bin/util/settingsUtil


# read options:
while [ "$1" != "" ]; do
	case "$1" in
		"--settings" )
			shift
			settingsDir="$1"
			;;
		* ) echo "unknown option!" ; exit 1
	esac
	shift
done
if [ "$settingsDir" != "" ]; then
	setSettingsFolder "$settingsDir"
	#if [ $? != 0 ]; then
		#echo "settings dir not found!"
		#exit 1
	#fi
fi
					
# create folder settings folder and file, if not yet existing:
init
if [ $? != "0" ]; then
	echo -en "settings folder not found!\ncreate one? (y/n)"
	read answer
	case $answer in
		y ) mkdir $SETTINGS_FOLDER
			> $SETTINGS_FILE ;;
		* ) exit 1 ;;
	esac
	init

fi

selection=
until [ "$selection" = "$CMD_EXIT" ]; do
	clear
	echo -e "************************************"
	echo -e "* sg_check.setup                   *"
	echo -e "************************************"
	echo -e "Current Settings:"
	echo -e "\t[1]: SERVER: $SERVER"
	echo -e "\t[2]: THIS: $THIS"
	echo -e "\t[3]: SERVER_BASE: $SERVER_BASE"
	echo -e "\t[4]: THIS_BASE: $THIS_BASE"
	echo "enter 1..4 to change a setting, or \"$CMD_EXIT\" to exit"
	echo -e "************************************"
	read selection
	case $selection in
		1 )
			echo -n "please enter ip for the SERVER: " 
			read SERVER
			;;
		2 ) 
			echo -n "please enter ip of this pc: " 
			read THIS
			;;
		3 ) 
			echo -n "please enter the base dir on the SERVER: " 
			read SERVER_BASE
			;;
		4 )
			echo -n "please enter the base dir on this pc: " 
			read THIS_BASE
			;;
		$CMD_EXIT ) ;;
		* ) echo "command not found!"
	esac
done

saveSettings
