#!/bin/bash

. "$SG_SCRIPT_PATH/sgcheck-bin/util/global"

#functions to work with files

# INFO
# the suffix ..List means: the operation does not touch the file itself,
# but just the list of managed files kept in the settings folder

# remove a file, and also remove it from the settings folder
function removeI
{
	if [ "$1" == "" ] ; then
		echo -n "enter filename: "
		read filename
	else
		filename=$1
	fi
	echo -n "are you shure? (y/n) "
	read answer
	case $answer in
		y ) ;;
		n ) return 0 ;;
		* ) echo "invalid input. quit current operation..." 
			return 1 ;;
	esac
	remove "$filename"
	removeFromList "$filename"
}



function addToList #$1:origin (relative to SERVER_BASE)
{
	local SRC="$1"
	echo "SRC: $SRC"
	# last component of filename:
	local baseNameTemp=$(basename "$SRC")
	#baseNameTemp="$($baseNameTemp)"
	local SRC_FILE="$baseNameTemp"
	#echo "SRC_FILE: $SRC_FILE"
	cd "$SETTINGS_FOLDER"
	> "$SRC_FILE.sg_descr"
	echo "ORIGIN=\"$SRC\"" >> "$SRC_FILE.sg_descr"
	return 0
}

# remove the file from the settings folder, but not the file itself
function removeFromListI
{
	if [ "$1" == "" ] ; then
		echo -n "enter filename: "
		read filename
		echo -n "are you shure? (y/n) "
		read answer
		case $answer in
			y ) ;;
			n ) return 0 ;;
			* ) echo "invalid input. quit current operation..." 
				return 1 ;;
		esac

	else
		filename="$1"
	fi
	
	removeFromList "$filename"
}


# just removes the file
# $1: the file to remove
# PRECONDITION: the file must exist!
function remove ()
{
	echo "executing 'rm -r \"$THIS_BASE$1\"'"
	rm -r "$THIS_BASE$1"
}

# remove a file from settings folder
# $1: the file to remove
# PRECONDITION: the file must exist!
function removeFromList ()
{
	echo "executing 'rm $SETTINGS_FOLDER$filename.sg_descr'"
	rm "$SETTINGS_FOLDER$1.sg_descr"
}
